/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hair(props) {
  const { nodes, materials } = useGLTF('/models/Hair.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hair.geometry}
 
        position={[0, 0.026, 0]}
        scale={1000}
      ><meshStandardMaterial color={"grey"}/></mesh>
    </group>
  )
}

useGLTF.preload('/models/Hair.gltf')
