/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Sewer(props) {
  const { nodes, materials } = useGLTF('/models/Sewer.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sewer.geometry}
        material={materials['Mat.1']}
        scale={25}
      />
    </group>
  )
}

useGLTF.preload('/models/Sewer.gltf')
 
